# Site settings
title: AIRESNUEVOSNQN
description: LA NUEVA VOZ DE LA NOTICIA
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
lang: es # <--- ¡Aquí está la línea añadida!

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-paginate-v2 # Plugin para paginación avanzada

# Paginación (jekyll-paginate-v2)
pagination:
  enabled: true
  per_page: 6 # Número de posts por página en las grillas de noticias
  permalink: '/page/:num/'
  title: ':title - Página :num'
  limit: 0
  offset: 0
  category: ':name'
  tag: ':name'
  locale: 'es' # Para que la paginación use texto en español
  sort_field: 'date'
  sort_reverse: true

# Defaults para los posts (útil para campos comunes)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post" # Layout por defecto para todos los posts
      author: "Redacciones AIRESNUEVOSNQN" # Autor por defecto
      image_description: "" # Descripción de imagen por defecto
      show_related_posts: true # Mostrar noticias relacionadas por defecto

# Configuración de categorías (opcional, Jekyll las genera automáticamente)
# Esto puede ser útil si quieres definir URLs amigables para categorías específicas
# Por ahora, Jekyll las maneja bien por defecto con la configuración de permalink de posts

# Configuración de fecha y hora
# timezone: America/Buenos_Aires # Comentada para evitar problemas en Windows

# Excluir archivos/carpetas de la compilación
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Archivos de inclusión (si tienes custom includes)
include:
  - _includes