# >>> COLECCIÓN 'PUBLICIDADES' OPTIMIZADA <<<
  - name: "ads"
    label: "Publicidades"
    editor:
      preview: false
    files:
      - file: "_data/ads.yml"
        label: "Gestión de Anuncios"
        name: "ads_data"
        fields:
          - label: "Anuncios de la Portada"
            name: "homepage_ads"
            widget: "object"
            fields:
              - label: "Anuncio Principal Superior (Desktop)"
                name: "main_top_desktop"
                widget: "object"
                fields:
                  - {label: "Imagen", name: "image", widget: "image", required: false}
                  - {label: "URL de Destino", name: "url", widget: "string", required: false}
                  - {label: "Texto Alternativo", name: "image_alt", widget: "string", required: false}
              - label: "Anuncio Principal Superior (Mobile)"
                name: "main_top_mobile"
                widget: "object"
                fields:
                  - {label: "Imagen", name: "image", widget: "image", required: false}
                  - {label: "URL de Destino", name: "url", widget: "string", required: false}
                  - {label: "Texto Alternativo", name: "image_alt", widget: "string", required: false}
          - label: "Anuncios de la Barra Lateral"
            name: "sidebar_ads"
            widget: "list"
            fields:
              - {label: "Título", name: "title", widget: "string"}
              - {label: "Imagen", name: "image", widget: "image"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "Texto Alternativo", name: "image_alt", widget: "string"}