# Configuración del Backend para Netlify Git Gateway
backend:
  name: git-gateway
  branch: main # O el nombre de tu rama principal (ej. master, si usas ese). Asegúrate que sea la rama que Netlify despliega.

# Configuración del sistema de autenticación
auth_base: .netlify/identity # Ruta para Netlify Identity
display_url: https://airesnuevosnqn.com # URL de tu sitio. ¡Asegúrate que esta sea tu URL real!

# Carpeta donde se subirán y gestionarán los archivos multimedia (imágenes, etc.)
media_folder: "assets/images" # Ruta relativa a la raíz del proyecto. Todas las imágenes subidas irán a esta carpeta.
public_folder: "/assets/images" # Ruta pública para acceder a las imágenes en tu sitio (lo que pones en <img src="...">).

# Colecciones de contenido (Tus tipos de noticias)
collections:
  - name: "posts" # Nombre interno para esta colección (ej. "posts")
    label: "Noticias" # Etiqueta que verás en el panel de Decap CMS para esta colección
    folder: "_posts" # Carpeta donde se guardarán TODOS los archivos Markdown de noticias
    create: true # Permite crear nuevas entradas en esta colección
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Formato de nombre de archivo (ej. 2025-07-30-mi-noticia.md)
    editor:
      preview: false # Deshabilita la previsualización en vivo. Puede ser útil si tu CSS es complejo y la previsualización no se ve bien.
    fields: # Los campos que aparecerán en el formulario para cada noticia, coincidiendo con tu front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"} # Campo oculto, siempre será 'post'
      - {label: "Antetítulo", name: "antetitulo", widget: "string", required: true}
      - {label: "Título", name: "title", widget: "string", required: true}
      - {label: "Autor", name: "author", widget: "string", default: "Redacción AIRESNUEVOSNQN"} # Valor por defecto para el autor
      - {label: "Fecha de Publicación", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss Z", default: "{{cms_now | date 'YYYY-MM-DD HH:mm:ss Z'}}"} # Fecha y hora actual por defecto
      - {label: "Categorías", name: "categories", widget: "list", default: ["ÚltimasNoticias"], hint: "Ej: Portada, Regionales, Política, Sociedad. La primera se usará para la URL de categoría y la navegación."}
      - {label: "Tags", name: "tags", widget: "list", hint: "Palabras clave separadas por comas. Ej: Neuquén, Elecciones, Economía."}
      - {label: "Noticia Principal de Portada", name: "featured", widget: "boolean", default: false, hint: "Marcar si esta noticia debe aparecer como principal en la portada (imagen grande)."} [cite: 2025-06-07]
      - {label: "Noticia Secundaria de Portada", name: "featured_secondary", widget: "boolean", default: false, hint: "Marcar si esta noticia debe aparecer como secundaria en la portada (imagen mediana)."} [cite: 2025-06-07]
      - {label: "Imagen", name: "image", widget: "image", required: true, hint: "La ruta se guardará relativa a /assets/images/. Sugerencia de tamaño: 800x600px (principal), 400x300px (secundaria), 400x225px (grillas)."} [cite: 2025-06-07]
      - {label: "Texto Alternativo Imagen", name: "image_alt", widget: "string", required: true, hint: "Texto descriptivo para la imagen (SEO y accesibilidad)."}
      - {label: "Pie de Imagen", name: "image_caption", widget: "string", hint: "Breve descripción que aparecerá debajo de la imagen."}
      - {label: "Copete", name: "copete", widget: "text", required: true} # Campo para el resumen de la noticia
      - {label: "Slug (URL amigable)", name: "slug", widget: "string", hint: "Se autocompleta con el título, pero puedes modificarlo para una URL más limpia."}
      - {label: "Cuerpo de la Noticia", name: "body", widget: "markdown", required: true} # Aseguramos que sea 'markdown'