# Configuración del Backend para Netlify Git Gateway
backend:
  name: git-gateway
  branch: main

auth_base: .netlify/identity
display_url: https://airesnuevosnqn.com

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Noticias"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Antetítulo", name: "antetitulo", widget: "string", required: true}
      - {label: "Título", name: "title", widget: "string", required: true}
      - {label: "Autor", name: "author", widget: "string", default: "Redacción AIRESNUEVOSNQN"}
      - {label: "Fecha de Publicación", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss Z", default: "{{cms_now | date 'YYYY-MM-DD HH:mm:ss Z'}}"}
      - {label: "Categorías", name: "categories", widget: "list", default: ["ÚltimasNoticias"], hint: "Ej: Portada, Regionales, Política, Sociedad."}
      - {label: "Tags", name: "tags", widget: "list", hint: "Palabras clave separadas por comas."}
      - {label: "Noticia Principal de Portada", name: "featured", widget: "boolean", default: false}
      - {label: "Noticia Secundaria de Portada", name: "featured_secondary", widget: "boolean", default: false}
      - {label: "Imagen", name: "image", widget: "image", required: true}
      - {label: "Texto Alternativo Imagen", name: "image_alt", widget: "string", required: true}
      - {label: "Pie de Imagen", name: "image_caption", widget: "string"}
      - {label: "SEO Título", name: "meta_title", widget: "string", required: false}
      - {label: "SEO Descripción", name: "meta_description", widget: "text", required: false}
      - {label: "Imagen para Redes Sociales", name: "social_image", widget: "image", required: false}
      - {label: "Copete", name: "copete", widget: "text", required: true}
      - {label: "Slug (URL amigable)", name: "slug", widget: "string"}
      - {label: "Cuerpo de la Noticia", name: "body", widget: "markdown", required: true}

  - name: "ads"
    label: "Publicidades"
    files:
      - file: "_data/ads.yml"
        label: "Lista de Publicidades"
        name: "ads_data"
        fields:
          - label: "Publicidades Activas"
            name: "ads"
            widget: "list"
            allow_add: true
            collapsible: true
            identifier_field: "title"
            fields:
              - {label: "Título (ID único)", name: "title", widget: "string", required: true}
              - {label: "Imagen (Desktop)", name: "image_desktop", widget: "image", required: false}
              - {label: "Imagen (Mobile)", name: "image_mobile", widget: "image", required: false}
              - {label: "Texto Alternativo Imagen", name: "image_alt", widget: "string", required: true}
              - {label: "URL de Destino", name: "url", widget: "string", required: true}
              - {label: "Fecha de Inicio", name: "start_date", widget: "datetime", required: false}
              - {label: "Fecha de Fin", name: "end_date", widget: "datetime", required: false}
